 #'base_discount_amount': '0.0000',
 #'base_discount_canceled': None,
 #'base_discount_invoiced': None,
 #'base_discount_refunded': None,
 #'base_grand_total': '71.8000',
 #'base_hidden_tax_amount': '0.0000',
 #'base_hidden_tax_invoiced': None,
 #'base_hidden_tax_refunded': None,
 #'base_shipping_amount': '50.0000',
 #'base_shipping_canceled': None,
 #'base_shipping_discount_amount': '0.0000',
 #'base_shipping_hidden_tax_amnt': '0.0000',
 #'base_shipping_hidden_tax_amount': '0.0000',
 #'base_shipping_incl_tax': '50.0000',
 #'base_shipping_invoiced': None,
 #'base_shipping_refunded': None,
 #'base_shipping_tax_amount': '0.0000',
 #'base_shipping_tax_refunded': None,
 #'base_subtotal': '20.0000',
 #'base_subtotal_canceled': None,
 #'base_subtotal_incl_tax': '21.8000',
 #'base_subtotal_invoiced': None,
 #'base_subtotal_refunded': None,
 #'base_tax_amount': '1.8000',
 #'base_tax_canceled': None,
 #'base_tax_invoiced': None,
 #'base_tax_refunded': None,
 #'base_to_global_rate': '1.0000',
 #'base_to_order_rate': '1.0000',
 #'base_total_canceled': None,
 #'base_total_due': None,
 #'base_total_invoiced': None,
 #'base_total_invoiced_cost': None,
 #'base_total_offline_refunded': None,
 #'base_total_online_refunded': None,
 #'base_total_paid': None,
 #'base_total_qty_ordered': None,
 #'base_total_refunded': None,

 #'billing_address_id': '7',
 #'billing_firstname': 'Joscha',
 #'billing_lastname': 'Krutzki',
 #'billing_name': 'Joscha Krutzki',

 #'can_ship_partially': None,
 #'can_ship_partially_item': None,

 #'coupon_code': None,
 #'coupon_rule_name': None,

 #'created_at': '2013-05-14 12:29:03',

 #'customer_dob': None,
 #'customer_email': 'joka@developlocal.sativa.jokasis.de',
 #'customer_firstname': 'Joscha',
 #'customer_gender': None,
 #'customer_group_id': '0',
 #'customer_id': None,
 #'customer_is_guest': '1',
 #'customer_lastname': 'Krutzki',
 #'customer_middlename': None,
 #'customer_note': None,
 #'customer_prefix': None,
 #'customer_suffix': None,
 #'customer_taxvat': None,

 #'discount_amount': '0.0000',
 #'discount_canceled': None,
 #'discount_description': None,
 #'discount_invoiced': None,
 #'discount_refunded': None,

 #'ext_customer_id': None,
 #'ext_order_id': None,

 #'firstname': 'VersandJosch',
 #'gift_message_id': None,
 #'global_currency_code': 'CHF',
 #'grand_total': '71.8000',
 #'hidden_tax_amount': '0.0000',
 #'hidden_tax_invoiced': None,
 #'hidden_tax_refunded': None,
 #'hold_before_state': None,
 #'hold_before_status': None,

 #'increment_id': '200000004',
 #'is_virtual': '0',
 #'lastname': 'VersandKrutzki',
 #'order_currency_code': 'CHF',

 #'payone_dunning_status': '',
 #'payone_payment_method_type': '',
 #'payone_transaction_status': '',
 #'paypal_ipn_customer_notified': '0',

 #'postcode': '13333',

 #'shipping_address_id': '8',
 #'shipping_amount': '50.0000',
 #'shipping_canceled': None,
 #'shipping_description': 'Flat Rate - Fixed',
 #'shipping_discount_amount': '0.0000',
 #'shipping_firstname': 'VersandJosch',
 #'shipping_hidden_tax_amount': '0.0000',
 #'shipping_incl_tax': '50.0000',
 #'shipping_invoiced': None,
 #'shipping_lastname': 'VersandKrutzki',
 #'shipping_method': 'flatrate_flatrate',
 #'shipping_name': 'VersandJosch VersandKrutzki',
 #'shipping_refunded': None,
 #'shipping_tax_amount': '0.0000',
 #'shipping_tax_refunded': None,

 #'state': 'new',
 #'store_name': 'ch_website\nch_hobby\nDeutsch',

 #'subtotal': '20.0000',
 #'subtotal_canceled': None,
 #'subtotal_incl_tax': '21.8000',
 #'subtotal_invoiced': None,
 #'subtotal_refunded': None,
 #'tax_amount': '1.8000',
 #'tax_canceled': None,
 #'tax_invoiced': None,
 #'tax_refunded': None,
 #'telephone': '123333',
 #'total_canceled': None,
 #'total_due': None,
 #'total_invoiced': None,
 #'total_item_count': '1',
 #'total_offline_refunded': None,
 #'total_online_refunded': None,
 #'total_paid': None,
 #'total_qty_ordered': '10.0000',
 #'total_refunded': None,
 #'weight': '2.5000',

